package providers

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"strings"
	"sync"
	"time"
)

// VaultKVVersion stores a single immutable revision of a secret in KV-v2.
type VaultKVVersion struct {
	Version   int
	Data      []byte
	CreatedAt time.Time
	Deleted   bool
}

// HashiCorpVaultProvider simulates a HashiCorp Vault client with KV-v2 and Transit engine support.
type HashiCorpVaultProvider struct {
	mu          sync.RWMutex
	address     string
	token       string
	kvStore     map[string][]VaultKVVersion
	transitKeys map[string][]byte
	mountPath   string
}

// NewHashiCorpVaultProvider initializes a Vault provider.
func NewHashiCorpVaultProvider(address, token, mountPath string) *HashiCorpVaultProvider {
	if mountPath == "" {
		mountPath = "secret/data"
	}
	return &HashiCorpVaultProvider{
		address:     address,
		token:       token,
		kvStore:     make(map[string][]VaultKVVersion),
		transitKeys: make(map[string][]byte),
		mountPath:   mountPath,
	}
}

func (h *HashiCorpVaultProvider) Name() string {
	return "hashicorp-vault"
}

// Authenticate verifies the configured client token.
func (h *HashiCorpVaultProvider) authenticate() error {
	if h.token == "" {
		return fmt.Errorf("%w: missing vault authentication token", ErrAccessDenied)
	}
	return nil
}

// PutSecret stores a new revision under KV-v2 engine.
func (h *HashiCorpVaultProvider) PutSecret(ctx context.Context, key string, value []byte) error {
	if err := h.authenticate(); err != nil {
		return err
	}

	h.mu.Lock()
	defer h.mu.Unlock()

	history := h.kvStore[key]
	newVer := len(history) + 1
	ver := VaultKVVersion{
		Version:   newVer,
		Data:      append([]byte(nil), value...),
		CreatedAt: time.Now().UTC(),
		Deleted:   false,
	}

	h.kvStore[key] = append(history, ver)
	return nil
}

// GetSecret fetches the latest undeleted version of a secret under KV-v2.
func (h *HashiCorpVaultProvider) GetSecret(ctx context.Context, key string) (*Secret, error) {
	if err := h.authenticate(); err != nil {
		return nil, err
	}

	h.mu.RLock()
	defer h.mu.RUnlock()

	history, exists := h.kvStore[key]
	if !exists || len(history) == 0 {
		return nil, fmt.Errorf("%w: vault path %s/%s not found", ErrSecretNotFound, h.mountPath, key)
	}

	// Latest version is at the end of the history
	latest := history[len(history)-1]
	if latest.Deleted {
		return nil, fmt.Errorf("%w: vault path %s/%s version %d marked deleted", ErrSecretNotFound, h.mountPath, key, latest.Version)
	}

	return &Secret{
		Key:   key,
		Value: append([]byte(nil), latest.Data...),
		Metadata: SecretMetadata{
			Key:       key,
			Version:   latest.Version,
			CreatedAt: latest.CreatedAt,
			Custom: map[string]string{
				"engine": "kv-v2",
				"mount":  h.mountPath,
			},
		},
	}, nil
}

// DeleteSecret marks the latest version of a secret as deleted.
func (h *HashiCorpVaultProvider) DeleteSecret(ctx context.Context, key string) error {
	if err := h.authenticate(); err != nil {
		return err
	}

	h.mu.Lock()
	defer h.mu.Unlock()

	history, exists := h.kvStore[key]
	if !exists || len(history) == 0 {
		return fmt.Errorf("%w: key %s not found", ErrSecretNotFound, key)
	}

	latestIdx := len(history) - 1
	h.kvStore[key][latestIdx].Deleted = true
	return nil
}

// ListSecrets returns all active (non-deleted) secret paths.
func (h *HashiCorpVaultProvider) ListSecrets(ctx context.Context) ([]string, error) {
	if err := h.authenticate(); err != nil {
		return nil, err
	}

	h.mu.RLock()
	defer h.mu.RUnlock()

	var active []string
	for k, hist := range h.kvStore {
		if len(hist) > 0 && !hist[len(hist)-1].Deleted {
			active = append(active, k)
		}
	}
	return active, nil
}

// TransitEncrypt encrypts plaintext using Vault Transit engine cipher key.
func (h *HashiCorpVaultProvider) TransitEncrypt(keyName string, plaintext []byte) (string, error) {
	if err := h.authenticate(); err != nil {
		return "", err
	}

	h.mu.Lock()
	defer h.mu.Unlock()

	transitKey, exists := h.transitKeys[keyName]
	if !exists {
		transitKey = make([]byte, 32)
		if _, err := rand.Read(transitKey); err != nil {
			return "", err
		}
		h.transitKeys[keyName] = transitKey
	}

	block, err := aes.NewCipher(transitKey)
	if err != nil {
		return "", err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", err
	}

	sealed := gcm.Seal(nonce, nonce, plaintext, nil)
	return fmt.Sprintf("vault:v1:%s", base64.StdEncoding.EncodeToString(sealed)), nil
}

// TransitDecrypt decrypts ciphertext previously generated by TransitEncrypt.
func (h *HashiCorpVaultProvider) TransitDecrypt(keyName string, cipherText string) ([]byte, error) {
	if err := h.authenticate(); err != nil {
		return nil, err
	}

	h.mu.RLock()
	transitKey, exists := h.transitKeys[keyName]
	h.mu.RUnlock()

	if !exists {
		return nil, fmt.Errorf("%w: transit key %q not found", ErrSecretNotFound, keyName)
	}

	if !strings.HasPrefix(cipherText, "vault:v1:") {
		return nil, fmt.Errorf("invalid transit ciphertext format")
	}

	rawB64 := strings.TrimPrefix(cipherText, "vault:v1:")
	rawBytes, err := base64.StdEncoding.DecodeString(rawB64)
	if err != nil {
		return nil, err
	}

	block, err := aes.NewCipher(transitKey)
	if err != nil {
		return nil, err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}

	nonceSize := gcm.NonceSize()
	if len(rawBytes) < nonceSize {
		return nil, fmt.Errorf("ciphertext too short")
	}

	nonce, payload := rawBytes[:nonceSize], rawBytes[nonceSize:]
	return gcm.Open(nil, nonce, payload, nil)
}
